### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by JamieSlome** [inoerp/inoERP#116]
Hi there,

I couldn't find a `SECURITY.md` in your repository and am not sure how to best contact you privately to disclose a security issue.

Can you add a `SECURITY.md` file with an e-mail to your repository, so that our system can send you the vulnerability details? GitHub suggests that a [security policy](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) is the best way to make sure security issues are responsibly disclosed.

Once you've done that, you should receive an e-mail within the next hour with more info.

Thanks! (cc @huntr-helper)

**Comment by kumarvivekpandey** [comment]
thank buddy what security issue plz tell

**Comment by JamieSlome** [comment]
@zidingz - bump 🤛

**Comment by zidingz** [comment]
Hey @kumarvivekpandey 

The issue is a [Cross-site Scripting (XSS) - Reflected](https://cwe.mitre.org/data/definitions/79.html).

In the interest of not disclosing security issues in public, would you consider adding an email to this [PR](https://github.com/inoerp/inoERP/pull/119)? We'll then send you the details.

Happy to help if you have any questions.

**Comment by inoerp** [comment]
Closing this issue as the Old PHP version is not maintained anymore, and the issue is irrelevant in the new Dart/Go application.
