### ISSUE TITLE
Sales order approvals

### ISSUE THREAD

**Issue by kchizi** [inoerp/inoERP#25]
Trying to learn the system, its comprehensive, i have noticed that Sales and distribution does not have any approvals and would like to understand why the business process for sales does not include approvals at any level..

**Comment by inoerp** [comment]
If you are looking for SO approval similar to PO approval, then it's not available because no business uses sales approval and no product (we consider Oracle 11i/R12/Fusion as the main benchmark)  provides that feature. Yes,  some big organizations use RMAs, Quotes, RFQs, etc. for approval but not for SO.

**Comment by kchizi** [comment]
understood, was comparing to SAP workflow
