### ISSUE TITLE
gettext module is required

### ISSUE THREAD

**Issue by sukantamanna84** [inoerp/inoERP#47]
Hi ,

I want to install inoerp on my shared hosting , 
Initially I was getting 
Fatal error: Cannot redeclare __() (previously declared in C:\localhost\inoERP-master\inoerp\locale\gettext.inc:290) in C:\localhost\inoERP-master\inoerp\locale\gettext.inc on line 505.

as per suggestion : http://inoideas.org/content/installation-problem?pageno=1&installation-problem
I comment out following lines.

function __($msgid) {
return ___($msgid);
}

to

// function __($msgid) {
// return ___($msgid);
// }

But Now I can navigate to Installation page one but asking me to fix the issue : "gettext module is required" . 

Please suggest 

Regards
Sukanta Manna

**Comment by ReactorShop** [comment]
I think the error is due to PHP not having the gettext module loaded.
If you are running Apache on Windows, you need to open C:\PHP\php.ini, or look for php.in in the correct location based on your setup, and remove the semicolon on the left on the row you find this:

`;extension=php_gettext.dll`

Then restart the Apache24 or Apache22 service, running services.msc from the command prompt

**Comment by dmoshi** [comment]
@ReactorShop Thank you so much this is the much needed fix
